language: python
python:
  - '3.6'
sudo: required
services:
  - docker
cache: pip
env:
  global:
    - DOCKER_USERNAME=captainfiaas
    - secure: bjTCM9RLCrzSl3m367TJFincEf9mBF04RnZdSkKhqr1dUEYX6YSu/ckiLDWfxpeu5zjoxbFiYZp4gBgGCncQVOPluHRAzGz9GXqvbiEKyN6PMObZQc8MzskGFU5eBTytrN+GuMmtsCwfvO72wsBa8Xh9jIipH//AkFmN8s68wOxkQssEnSHdLjLnObjjo30njKNR1yz3/RiLgC64VPw4hXbIGHYCNZbfX3udzSYVrkCGCTj0JZcYKVjC6lkI/HWwr5zbp3wp0UjN2Uj+eWXZM9sFdKVegcG32RlR+994FhUniw6oWNe6w2WN/DMLIkk9MqVW87myq01F1ut22ZhKHExYRdwnasa+R4KcKa4AsrGoRvWnse3cgGAcekWRokGrY8TkdDww508bKaAlwLh5jJN3qfZcfocAWsI9gqEt6DQMEJ7/YH1nQLA7AOBmkvu7jegL51uRgv4EgiI9JYgkXON4Rj3Ma7IG8EqLXJ+DaM6TppGYa6U5bUmPuLR+EPb9RjiGqBX8Dx9RY1eiaD6JiIW1B6/jDyhDoFKJNmvbeO+u7tjyr1c+tJFHrMPFZmIMZRyMud5jPPH4pHhewCDgwnb/kiZQT3TalPNBsN1B6HEQbAc9ZF3FDkLZYoNzcsh3P9kCFzQn+YTk70siB3Ko2Xnl1/BY9WvDcvE6Co/WBzU= # DOCKER_PASSWORD
before_install:
  - sudo rm -f /etc/boto.cfg # Fix to avoid problems importing boto
install:
  - pip install -e .[ci]
script:
  - tox
  - bin/docker_build
after_success: tox -e coverage
deploy:
  provider: script
  script: bin/docker_push && bin/tag_release
  skip_cleanup: true
  on:
    branch: master
